# Site settings
title: Everything is awsome
email: thomasdam@mac.com
description: > # this means to ignore newlines until "baseurl:"
  Everything is awesome, for awsome people
url: "http://thomas-dam.github.io" # the base hostname & protocol for your site
twitter_username: thomas_dam
github_username:  thomas-dam

# Build settings
markdown: kramdown
highlighter: pygments
excerpt_separator: ""

